In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 20)

In [2]:
customers = pd.read_csv("/Users/rohithjavvadi/Downloads/archive (1)/olist_customers_dataset.csv")

geolocation = pd.read_csv("/Users/rohithjavvadi/Downloads/archive (1)/olist_geolocation_dataset.csv")

orders = pd.read_csv("/Users/rohithjavvadi/Downloads/archive (1)/olist_orders_dataset.csv")

order_items = pd.read_csv("/Users/rohithjavvadi/Downloads/archive (1)/olist_order_items_dataset.csv")

payments = pd.read_csv("/Users/rohithjavvadi/Downloads/archive (1)/olist_order_payments_dataset.csv")

reviews = pd.read_csv("/Users/rohithjavvadi/Downloads/archive (1)/olist_order_reviews_dataset.csv")

products = pd.read_csv("/Users/rohithjavvadi/Downloads/archive (1)/olist_products_dataset.csv")

sellers = pd.read_csv("/Users/rohithjavvadi/Downloads/archive (1)/olist_sellers_dataset.csv")

category_translation = pd.read_csv(
    "/Users/rohithjavvadi/Downloads/archive (1)/product_category_name_translation.csv"
)

In [3]:
#
datasets = {
    "customers": customers,
    "geolocation": geolocation,
    "orders": orders,
    "order_items": order_items,
    "payments": payments,
    "reviews": reviews,
    "products": products,
    "sellers": sellers,
    "category_translation": category_translation
}

In [4]:
for name, df in datasets.items():
    print("=" * 70)
    print(name.upper())
    print("=" * 70)

    print(df.head())

    print("\nShape:")
    print(df.shape)

    print("\nColumns:")
    print(df.columns.tolist())

    print("\n")

======================================================================
CUSTOMERS
======================================================================
                        customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066

   customer_zip_code_prefix          customer_city customer_state
0                     14409                 franca             SP
1                      9790  sao bernardo do campo             SP
2                      1151              sao paulo             SP
3                      8775        mogi das cruzes             SP
4                     13056               campinas             SP

Shape:
(99441, 5)

Columns:
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']


======================================================================
GEOLOCATION
======================================================================
   geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                         1037       -23.545621       -46.639292
1                         1046       -23.546081       -46.644820
2                         1046       -23.546129       -46.642951
3                         1041       -23.544392       -46.639499
4                         1035       -23.541578       -46.641607

  geolocation_city geolocation_state
0        sao paulo                SP
1        sao paulo                SP
2        sao paulo                SP
3        sao paulo                SP
4        sao paulo                SP

Shape:
(1000163, 5)

Columns:
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']


======================================================================
ORDERS
======================================================================
                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c

  order_status order_purchase_timestamp    order_approved_at  \
0    delivered      2017-10-02 10:56:33  2017-10-02 11:07:15
1    delivered      2018-07-24 20:41:37  2018-07-26 03:24:27
2    delivered      2018-08-08 08:38:49  2018-08-08 08:55:23
3    delivered      2017-11-18 19:28:06  2017-11-18 19:45:59
4    delivered      2018-02-13 21:18:39  2018-02-13 22:20:29

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13
1          2018-07-26 14:31:00           2018-08-07 15:27:45
2          2018-08-08 13:50:00           2018-08-17 18:06:29
3          2017-11-22 13:39:59           2017-12-02 00:28:42
4          2018-02-14 19:46:34           2018-02-16 18:17:02

  order_estimated_delivery_date
0           2017-10-18 00:00:00
1           2018-08-13 00:00:00
2           2018-09-04 00:00:00
3           2017-12-15 00:00:00
4           2018-02-26 00:00:00

Shape:
(99441, 8)

Columns:
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']


======================================================================
ORDER_ITEMS
======================================================================
                           order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1
1  00018f77f2f0320c557190d7a144bdd3              1
2  000229ec398224ef6ca0657da4fc703e              1
3  00024acbcdf0a6daa1e931b038114c75              1
4  00042b26cf59d7ce69dfabb4e55b4fd9              1

                         product_id                         seller_id  \
0  4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202
1  e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36
2  c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d
3  7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4
4  ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87

   shipping_limit_date   price  freight_value
0  2017-09-19 09:45:35   58.90          13.29
1  2017-05-03 11:05:13  239.90          19.93
2  2018-01-18 14:48:30  199.00          17.87
3  2018-08-15 10:10:18   12.99          12.79
4  2017-02-13 13:57:51  199.90          18.14

Shape:
(112650, 7)

Columns:
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']


======================================================================
PAYMENTS
======================================================================
                           order_id  payment_sequential payment_type  \
0  b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card
1  a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card
2  25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card
3  ba78997921bbcdc1373bb41e913ab953                   1  credit_card
4  42fdf880ba16b47b59251dd489d4441a                   1  credit_card

   payment_installments  payment_value
0                     8          99.33
1                     1          24.39
2                     1          65.71
3                     8         107.78
4                     2         128.45

Shape:
(103886, 5)

Columns:
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']


======================================================================
REVIEWS
======================================================================
                          review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b
3  e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b
4  f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1

   review_score review_comment_title  \
0             4                  NaN
1             5                  NaN
2             5                  NaN
3             5                  NaN
4             5                  NaN

                              review_comment_message review_creation_date  \
0                                                NaN  2018-01-18 00:00:00
1                                                NaN  2018-03-10 00:00:00
2                                                NaN  2018-02-17 00:00:00
3              Recebi bem antes do prazo estipulado.  2017-04-21 00:00:00
4  Parabéns lojas lannister adorei comprar pela I...  2018-03-01 00:00:00

  review_answer_timestamp
0     2018-01-18 21:46:59
1     2018-03-11 03:05:13
2     2018-02-18 14:36:24
3     2017-04-21 22:02:06
4     2018-03-02 10:26:53

Shape:
(99224, 7)

Columns:
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']


======================================================================
PRODUCTS
======================================================================
                         product_id  product_category_name  \
0  1e9e8ef04dbcff4541ed26657ea517e5             perfumaria
1  3aa071139cb16b67ca9e5dea641aaa2f                  artes
2  96bd76ec8810374ed1b65e291975717f          esporte_lazer
3  cef67bcfe19066a932b7673e239eb23d                  bebes
4  9dc1a7de274444849c219cff195d0b71  utilidades_domesticas

   product_name_lenght  product_description_lenght  product_photos_qty  \
0                 40.0                       287.0                 1.0
1                 44.0                       276.0                 1.0
2                 46.0                       250.0                 1.0
3                 27.0                       261.0                 1.0
4                 37.0                       402.0                 4.0

   product_weight_g  product_length_cm  product_height_cm  product_width_cm
0             225.0               16.0               10.0              14.0
1            1000.0               30.0               18.0              20.0
2             154.0               18.0                9.0              15.0
3             371.0               26.0                4.0              26.0
4             625.0               20.0               17.0              13.0

Shape:
(32951, 9)

Columns:
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']


======================================================================
SELLERS
======================================================================
                          seller_id  seller_zip_code_prefix  \
0  3442f8959a84dea7ee197c632cb2df15                   13023
1  d1b65fc7debc3361ea86b5f14c68d2e2                   13844
2  ce3ad9de960102d0677a81f5d0bb7b2d                   20031
3  c0f3eea2e14555b6faeea3dd58c1b1c3                    4195
4  51a04a8a6bdcb23deccc82b0b80742cf                   12914

         seller_city seller_state
0           campinas           SP
1         mogi guacu           SP
2     rio de janeiro           RJ
3          sao paulo           SP
4  braganca paulista           SP

Shape:
(3095, 4)

Columns:
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']


======================================================================
CATEGORY_TRANSLATION
======================================================================
    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

Shape:
(71, 2)

Columns:
['product_category_name', 'product_category_name_english']

In [5]:
for name, df in datasets.items():

    print("=" * 70)
    print(name.upper())

    print(df.dtypes)
    

    print("\n")

======================================================================
CUSTOMERS
customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object


======================================================================
GEOLOCATION
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object


======================================================================
ORDERS
order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object


======================================================================
ORDER_ITEMS
order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object


======================================================================
PAYMENTS
order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object


======================================================================
REVIEWS
review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object


======================================================================
PRODUCTS
product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object


======================================================================
SELLERS
seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object


======================================================================
CATEGORY_TRANSLATION
product_category_name            object
product_category_name_english    object
dtype: object

In [6]:
for name, df in datasets.items():

    print("=" * 70)
    print(name.upper())

    missing = df.isnull().sum()

    missing = missing[missing > 0]

    print(missing.sort_values(ascending=False))

    print("\n")

======================================================================
CUSTOMERS
Series([], dtype: int64)


======================================================================
GEOLOCATION
Series([], dtype: int64)


======================================================================
ORDERS
order_delivered_customer_date    2965
order_delivered_carrier_date     1783
order_approved_at                 160
dtype: int64


======================================================================
ORDER_ITEMS
Series([], dtype: int64)


======================================================================
PAYMENTS
Series([], dtype: int64)


======================================================================
REVIEWS
review_comment_title      87656
review_comment_message    58247
dtype: int64


======================================================================
PRODUCTS
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64


======================================================================
SELLERS
Series([], dtype: int64)


======================================================================
CATEGORY_TRANSLATION
Series([], dtype: int64)

In [7]:
for name, df in datasets.items():

    duplicates = df.duplicated().sum()

    print(f"{name}: {duplicates}")

customers: 0
geolocation: 261831
orders: 0
order_items: 0
payments: 0
reviews: 0
products: 0
sellers: 0
category_translation: 0

In [8]:
for name, df in datasets.items():

    print("=" * 70)

    print(name.upper())

    print(df.describe())

======================================================================
CUSTOMERS
       customer_zip_code_prefix
count              99441.000000
mean               35137.474583
std                29797.938996
min                 1003.000000
25%                11347.000000
50%                24416.000000
75%                58900.000000
max                99990.000000
======================================================================
GEOLOCATION
       geolocation_zip_code_prefix  geolocation_lat  geolocation_lng
count                 1.000163e+06     1.000163e+06     1.000163e+06
mean                  3.657417e+04    -2.117615e+01    -4.639054e+01
std                   3.054934e+04     5.715866e+00     4.269748e+00
min                   1.001000e+03    -3.660537e+01    -1.014668e+02
25%                   1.107500e+04    -2.360355e+01    -4.857317e+01
50%                   2.653000e+04    -2.291938e+01    -4.663788e+01
75%                   6.350400e+04    -1.997962e+01    -4.376771e+01
max                   9.999000e+04     4.506593e+01     1.211054e+02
======================================================================
ORDERS
                                order_id                       customer_id  \
count                              99441                             99441
unique                             99441                             99441
top     e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
freq                                   1                                 1

       order_status order_purchase_timestamp    order_approved_at  \
count         99441                    99441                99281
unique            8                    98875                90733
top       delivered      2018-04-11 10:48:14  2018-02-27 04:31:10
freq          96478                        3                    9

       order_delivered_carrier_date order_delivered_customer_date  \
count                         97658                         96476
unique                        81018                         95664
top             2018-05-09 15:48:00           2018-05-08 23:38:46
freq                             47                             3

       order_estimated_delivery_date
count                          99441
unique                           459
top              2017-12-20 00:00:00
freq                             522
======================================================================
ORDER_ITEMS
       order_item_id          price  freight_value
count  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320
std         0.705124     183.633928      15.806405
min         1.000000       0.850000       0.000000
25%         1.000000      39.900000      13.080000
50%         1.000000      74.990000      16.260000
75%         1.000000     134.900000      21.150000
max        21.000000    6735.000000     409.680000
======================================================================
PAYMENTS
       payment_sequential  payment_installments  payment_value
count       103886.000000         103886.000000  103886.000000
mean             1.092679              2.853349     154.100380
std              0.706584              2.687051     217.494064
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      56.790000
50%              1.000000              1.000000     100.000000
75%              1.000000              4.000000     171.837500
max             29.000000             24.000000   13664.080000
======================================================================
REVIEWS
       review_score
count  99224.000000
mean       4.086421
std        1.347579
min        1.000000
25%        4.000000
50%        5.000000
75%        5.000000
max        5.000000
======================================================================
PRODUCTS
       product_name_lenght  product_description_lenght  product_photos_qty  \
count         32341.000000                32341.000000        32341.000000
mean             48.476949                  771.495285            2.188986
std              10.245741                  635.115225            1.736766
min               5.000000                    4.000000            1.000000
25%              42.000000                  339.000000            1.000000
50%              51.000000                  595.000000            1.000000
75%              57.000000                  972.000000            3.000000
max              76.000000                 3992.000000           20.000000

       product_weight_g  product_length_cm  product_height_cm  \
count      32949.000000       32949.000000       32949.000000
mean        2276.472488          30.815078          16.937661
std         4282.038731          16.914458          13.637554
min            0.000000           7.000000           2.000000
25%          300.000000          18.000000           8.000000
50%          700.000000          25.000000          13.000000
75%         1900.000000          38.000000          21.000000
max        40425.000000         105.000000         105.000000

       product_width_cm
count      32949.000000
mean          23.196728
std           12.079047
min            6.000000
25%           15.000000
50%           20.000000
75%           30.000000
max          118.000000
======================================================================
SELLERS
       seller_zip_code_prefix
count             3095.000000
mean             32291.059451
std              32713.453830
min               1001.000000
25%               7093.500000
50%              14940.000000
75%              64552.500000
max              99730.000000
======================================================================
CATEGORY_TRANSLATION
       product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1

In [9]:
for name, df in datasets.items():

    print("=" * 70)

    print(name.upper())

    print(df.describe(include="object"))

======================================================================
CUSTOMERS
                             customer_id                customer_unique_id  \
count                              99441                             99441
unique                             99441                             96096
top     06b8999e2fba1a1fbc88172c00ba8bc7  8d50f5eadf50201ccdcedfb9e2ac8455
freq                                   1                                17

       customer_city customer_state
count          99441          99441
unique          4119             27
top        sao paulo             SP
freq           15540          41746
======================================================================
GEOLOCATION
       geolocation_city geolocation_state
count           1000163           1000163
unique             8011                27
top           sao paulo                SP
freq             135800            404268
======================================================================
ORDERS
                                order_id                       customer_id  \
count                              99441                             99441
unique                             99441                             99441
top     e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
freq                                   1                                 1

       order_status order_purchase_timestamp    order_approved_at  \
count         99441                    99441                99281
unique            8                    98875                90733
top       delivered      2018-04-11 10:48:14  2018-02-27 04:31:10
freq          96478                        3                    9

       order_delivered_carrier_date order_delivered_customer_date  \
count                         97658                         96476
unique                        81018                         95664
top             2018-05-09 15:48:00           2018-05-08 23:38:46
freq                             47                             3

       order_estimated_delivery_date
count                          99441
unique                           459
top              2017-12-20 00:00:00
freq                             522
======================================================================
ORDER_ITEMS
                                order_id                        product_id  \
count                             112650                            112650
unique                             98666                             32951
top     8272b63d03f5f79c56e9e4120aec44ef  aca2eb7d00ea1a7b8ebd4e68314663af
freq                                  21                               527

                               seller_id  shipping_limit_date
count                             112650               112650
unique                              3095                93318
top     6560211a19b47992c3666cc44a7e94c0  2017-07-21 18:25:23
freq                                2033                   21
======================================================================
PAYMENTS
                                order_id payment_type
count                             103886       103886
unique                             99440            5
top     fa65dad1b0e818e3ccc5cb0e39231352  credit_card
freq                                  29        76795
======================================================================
REVIEWS
                               review_id                          order_id  \
count                              99224                             99224
unique                             98410                             98673
top     7b606b0d57b078384f0b58eac1d41d78  c88b1d1b157a9999ce368f218a407141
freq                                   3                                 3

       review_comment_title review_comment_message review_creation_date  \
count                 11568                  40977                99224
unique                 4527                  36159                  636
top               Recomendo              Muito bom  2017-12-19 00:00:00
freq                    423                    230                  463

       review_answer_timestamp
count                    99224
unique                   98248
top        2017-06-15 23:21:05
freq                         4
======================================================================
PRODUCTS
                              product_id product_category_name
count                              32951                 32341
unique                             32951                    73
top     1e9e8ef04dbcff4541ed26657ea517e5       cama_mesa_banho
freq                                   1                  3029
======================================================================
SELLERS
                               seller_id seller_city seller_state
count                               3095        3095         3095
unique                              3095         611           23
top     3442f8959a84dea7ee197c632cb2df15   sao paulo           SP
freq                                   1         694         1849
======================================================================
CATEGORY_TRANSLATION
       product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1

In [10]:
for name, df in datasets.items():
    print("=" * 70)
    print(f"TABLE: {name.upper()}")
    print("=" * 70)

    summary = pd.DataFrame({
        "Column": df.columns,
        "Data Type": df.dtypes.values,
        "Missing Values": df.isnull().sum().values,
        "Unique Values": df.nunique().values
    })

    display(summary)

======================================================================
TABLE: CUSTOMERS
======================================================================

                     Column Data Type  Missing Values  Unique Values
0               customer_id    object               0          99441
1        customer_unique_id    object               0          96096
2  customer_zip_code_prefix     int64               0          14994
3             customer_city    object               0           4119
4            customer_state    object               0             27

======================================================================
TABLE: GEOLOCATION
======================================================================

                        Column Data Type  Missing Values  Unique Values
0  geolocation_zip_code_prefix     int64               0          19015
1              geolocation_lat   float64               0         717363
2              geolocation_lng   float64               0         717615
3             geolocation_city    object               0           8011
4            geolocation_state    object               0             27

======================================================================
TABLE: ORDERS
======================================================================

                          Column Data Type  Missing Values  Unique Values
0                       order_id    object               0          99441
1                    customer_id    object               0          99441
2                   order_status    object               0              8
3       order_purchase_timestamp    object               0          98875
4              order_approved_at    object             160          90733
5   order_delivered_carrier_date    object            1783          81018
6  order_delivered_customer_date    object            2965          95664
7  order_estimated_delivery_date    object               0            459

======================================================================
TABLE: ORDER_ITEMS
======================================================================

                Column Data Type  Missing Values  Unique Values
0             order_id    object               0          98666
1        order_item_id     int64               0             21
2           product_id    object               0          32951
3            seller_id    object               0           3095
4  shipping_limit_date    object               0          93318
5                price   float64               0           5968
6        freight_value   float64               0           6999

======================================================================
TABLE: PAYMENTS
======================================================================

                 Column Data Type  Missing Values  Unique Values
0              order_id    object               0          99440
1    payment_sequential     int64               0             29
2          payment_type    object               0              5
3  payment_installments     int64               0             24
4         payment_value   float64               0          29077

======================================================================
TABLE: REVIEWS
======================================================================

                    Column Data Type  Missing Values  Unique Values
0                review_id    object               0          98410
1                 order_id    object               0          98673
2             review_score     int64               0              5
3     review_comment_title    object           87656           4527
4   review_comment_message    object           58247          36159
5     review_creation_date    object               0            636
6  review_answer_timestamp    object               0          98248

======================================================================
TABLE: PRODUCTS
======================================================================

                       Column Data Type  Missing Values  Unique Values
0                  product_id    object               0          32951
1       product_category_name    object             610             73
2         product_name_lenght   float64             610             66
3  product_description_lenght   float64             610           2960
4          product_photos_qty   float64             610             19
5            product_weight_g   float64               2           2204
6           product_length_cm   float64               2             99
7           product_height_cm   float64               2            102
8            product_width_cm   float64               2             95

======================================================================
TABLE: SELLERS
======================================================================

                   Column Data Type  Missing Values  Unique Values
0               seller_id    object               0           3095
1  seller_zip_code_prefix     int64               0           2246
2             seller_city    object               0            611
3            seller_state    object               0             23

======================================================================
TABLE: CATEGORY_TRANSLATION
======================================================================

                          Column Data Type  Missing Values  Unique Values
0          product_category_name    object               0             71
1  product_category_name_english    object               0             71

In [11]:
for name, df in datasets.items():
    print("=" * 70)
    print(name.upper())

    for column in df.columns:
        if df[column].is_unique:
            print(f"{column} → Candidate Primary Key")

======================================================================
CUSTOMERS
customer_id → Candidate Primary Key
======================================================================
GEOLOCATION
======================================================================
ORDERS
order_id → Candidate Primary Key
customer_id → Candidate Primary Key
======================================================================
ORDER_ITEMS
======================================================================
PAYMENTS
======================================================================
REVIEWS
======================================================================
PRODUCTS
product_id → Candidate Primary Key
======================================================================
SELLERS
seller_id → Candidate Primary Key
======================================================================
CATEGORY_TRANSLATION
product_category_name → Candidate Primary Key
product_category_name_english → Candidate Primary Key

In [12]:
order_items["order_id"].isin(orders["order_id"]).all()

order_items["product_id"].isin(products["product_id"]).all()

order_items["seller_id"].isin(sellers["seller_id"]).all()

payments["order_id"].isin(orders["order_id"]).all()

reviews["order_id"].isin(orders["order_id"]).all()

np.True_

In [13]:
for name, df in datasets.items():
    print("=" * 70)
    print(name.upper())

    date_columns = [
        col for col in df.columns
        if "date" in col.lower() or "timestamp" in col.lower()
    ]

    print(date_columns)

======================================================================
CUSTOMERS
[]
======================================================================
GEOLOCATION
[]
======================================================================
ORDERS
['order_purchase_timestamp', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']
======================================================================
ORDER_ITEMS
['shipping_limit_date']
======================================================================
PAYMENTS
[]
======================================================================
REVIEWS
['review_creation_date', 'review_answer_timestamp']
======================================================================
PRODUCTS
[]
======================================================================
SELLERS
[]
======================================================================
CATEGORY_TRANSLATION
[]